# conda env create -f environment.yml
name: data-challenge
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    # python version
    - python=3.9

    # conda packages
    - numpy=1.20
    - pandas=1.1
    - seaborn=0.11
    - scipy=1.6
    - jupyterlab=3.0
